function plotPyrNeuWithFieldStimStats_subPop(pathAnal0,PyrRunOnAct,xlabels,fnstr)

    colorSel = 0;
    xLimTmp = [0 4];

    %% activation
    barPlotWithStat1(1:2,...
        [mean(PyrRunOnAct.meanAvgFRProfileAll_NonStimCtrl_Act),...
        mean(PyrRunOnAct.meanAvgFRProfileAll_Stim_Act)],...
        [std(PyrRunOnAct.meanAvgFRProfileAll_NonStimCtrl_Act)...
            /sqrt(length(PyrRunOnAct.meanAvgFRProfileAll_NonStimCtrl_Act)),...
        std(PyrRunOnAct.meanAvgFRProfileAll_Stim_Act)...
            /sqrt(length(PyrRunOnAct.meanAvgFRProfileAll_Stim_Act))],...
        [PyrRunOnAct.meanAvgFRProfileAll_NonStimCtrl_Act,...
        PyrRunOnAct.meanAvgFRProfileAll_Stim_Act],...
        ['FRMean All' fnstr ' Act'],...
        '', PyrRunOnAct.pRSAvgFRProfileAll_NonStimStim_Act,...
        ['FRMeanAllGoodNoStimVsStim_' fnstr '_Act'],...
        pathAnal0,colorSel,xlabels,xLimTmp);

    %% FR mean of each segment
    barPlotWithStat1(1:2,...
        [mean(PyrRunOnAct.meanAvgFRProfileBefRun_NonStimCtrl_Act),...
        mean(PyrRunOnAct.meanAvgFRProfileBefRun_Stim_Act)],...
        [std(PyrRunOnAct.meanAvgFRProfileBefRun_NonStimCtrl_Act)...
            /sqrt(length(PyrRunOnAct.meanAvgFRProfileBefRun_NonStimCtrl_Act)),...
        std(PyrRunOnAct.meanAvgFRProfileBefRun_Stim_Act)...
            /sqrt(length(PyrRunOnAct.meanAvgFRProfileBefRun_Stim_Act))],...
        [PyrRunOnAct.meanAvgFRProfileBefRun_NonStimCtrl_Act,...
        PyrRunOnAct.meanAvgFRProfileBefRun_Stim_Act],...
        ['FRMean BefRun' fnstr ' Act'],...
        '', PyrRunOnAct.pRSAvgFRProfileBefRun_NonStimStim_Act,...
        ['FRMeanBefRunGoodNoStimVsStim_' fnstr '_Act'],...
        pathAnal0,colorSel,xlabels,xLimTmp);
    
    barPlotWithStat1(1:2,...
        [mean(PyrRunOnAct.meanAvgFRProfile0to1st_NonStimCtrl_Act),...
        mean(PyrRunOnAct.meanAvgFRProfile0to1st_Stim_Act)],...
        [std(PyrRunOnAct.meanAvgFRProfile0to1st_NonStimCtrl_Act)...
            /sqrt(length(PyrRunOnAct.meanAvgFRProfile0to1st_NonStimCtrl_Act)),...
        std(PyrRunOnAct.meanAvgFRProfile0to1st_Stim_Act)...
            /sqrt(length(PyrRunOnAct.meanAvgFRProfile0to1st_Stim_Act))],...
        [PyrRunOnAct.meanAvgFRProfile0to1st_NonStimCtrl_Act,...
        PyrRunOnAct.meanAvgFRProfile0to1st_Stim_Act],...
        ['FRMean 0to1st' fnstr ' Act'],...
        '', PyrRunOnAct.pRSAvgFRProfile0to1st_NonStimStim_Act,...
        ['FRMean0to1stGoodNoStimVsStim' fnstr '_Act'],...
        pathAnal0,colorSel,xlabels,xLimTmp);

    barPlotWithStat1(1:2,...
        [mean(PyrRunOnAct.meanAvgFRProfile2to3s_NonStimCtrl_Act),...
        mean(PyrRunOnAct.meanAvgFRProfile2to3s_Stim_Act)],...
        [std(PyrRunOnAct.meanAvgFRProfile2to3s_NonStimCtrl_Act)...
            /sqrt(length(PyrRunOnAct.meanAvgFRProfile2to3s_NonStimCtrl_Act)),...
        std(PyrRunOnAct.meanAvgFRProfile2to3s_Stim_Act)...
            /sqrt(length(PyrRunOnAct.meanAvgFRProfile2to3s_Stim_Act))],...
        [PyrRunOnAct.meanAvgFRProfile2to3s_NonStimCtrl_Act,...
        PyrRunOnAct.meanAvgFRProfile2to3s_Stim_Act],...
        ['FRMean 2to3s' fnstr ' Act'],...
        '', PyrRunOnAct.pRSAvgFRProfile2to3s_NonStimStim_Act,...
        ['FRMean2to3sGoodNoStimVsStim' fnstr '_Act'],...
        pathAnal0,colorSel,xlabels,xLimTmp);

    %% inactivation
    barPlotWithStat1(1:2,...
        [mean(PyrRunOnAct.meanAvgFRProfileAll_NonStimCtrl_Inact),...
        mean(PyrRunOnAct.meanAvgFRProfileAll_Stim_Inact)],...
        [std(PyrRunOnAct.meanAvgFRProfileAll_NonStimCtrl_Inact)...
            /sqrt(length(PyrRunOnAct.meanAvgFRProfileAll_NonStimCtrl_Inact)),...
        std(PyrRunOnAct.meanAvgFRProfileAll_Stim_Inact)...
            /sqrt(length(PyrRunOnAct.meanAvgFRProfileAll_Stim_Inact))],...
        [PyrRunOnAct.meanAvgFRProfileAll_NonStimCtrl_Inact,...
        PyrRunOnAct.meanAvgFRProfileAll_Stim_Inact],...
        ['FRMean All' fnstr ' Inact'],...
        '', PyrRunOnAct.pRSAvgFRProfileAll_NonStimStim_Inact,...
        ['FRMeanAllGoodNoStimVsStim_' fnstr '_Inact'],...
        pathAnal0,colorSel,xlabels,xLimTmp);

    %% FR mean of each segment
    barPlotWithStat1(1:2,...
        [mean(PyrRunOnAct.meanAvgFRProfileBefRun_NonStimCtrl_Inact),...
        mean(PyrRunOnAct.meanAvgFRProfileBefRun_Stim_Inact)],...
        [std(PyrRunOnAct.meanAvgFRProfileBefRun_NonStimCtrl_Inact)...
            /sqrt(length(PyrRunOnAct.meanAvgFRProfileBefRun_NonStimCtrl_Inact)),...
        std(PyrRunOnAct.meanAvgFRProfileBefRun_Stim_Inact)...
            /sqrt(length(PyrRunOnAct.meanAvgFRProfileBefRun_Stim_Inact))],...
        [PyrRunOnAct.meanAvgFRProfileBefRun_NonStimCtrl_Inact,...
        PyrRunOnAct.meanAvgFRProfileBefRun_Stim_Inact],...
        ['FRMean BefRun' fnstr ' Inact'],...
        '', PyrRunOnAct.pRSAvgFRProfileBefRun_NonStimStim_Inact,...
        ['FRMeanBefRunGoodNoStimVsStim_' fnstr '_Inact'],...
        pathAnal0,colorSel,xlabels,xLimTmp);
        
    barPlotWithStat1(1:2,...
        [mean(PyrRunOnAct.meanAvgFRProfile0to1st_NonStimCtrl_Inact),...
        mean(PyrRunOnAct.meanAvgFRProfile0to1st_Stim_Inact)],...
        [std(PyrRunOnAct.meanAvgFRProfile0to1st_NonStimCtrl_Inact)...
            /sqrt(length(PyrRunOnAct.meanAvgFRProfile0to1st_NonStimCtrl_Inact)),...
        std(PyrRunOnAct.meanAvgFRProfile0to1st_Stim_Inact)...
            /sqrt(length(PyrRunOnAct.meanAvgFRProfile0to1st_Stim_Inact))],...
        [PyrRunOnAct.meanAvgFRProfile0to1st_NonStimCtrl_Inact,...
        PyrRunOnAct.meanAvgFRProfile0to1st_Stim_Inact],...
        ['FRMean 0to1st' fnstr ' Inact'],...
        '', PyrRunOnAct.pRSAvgFRProfile0to1st_NonStimStim_Inact,...
        ['FRMean0to1stGoodNoStimVsStim' fnstr '_Inact'],...
        pathAnal0,colorSel,xlabels,xLimTmp);

    barPlotWithStat1(1:2,...
        [mean(PyrRunOnAct.meanAvgFRProfile2to3s_NonStimCtrl_Inact),...
        mean(PyrRunOnAct.meanAvgFRProfile2to3s_Stim_Inact)],...
        [std(PyrRunOnAct.meanAvgFRProfile2to3s_NonStimCtrl_Inact)...
            /sqrt(length(PyrRunOnAct.meanAvgFRProfile2to3s_NonStimCtrl_Inact)),...
        std(PyrRunOnAct.meanAvgFRProfile2to3s_Stim_Inact)...
            /sqrt(length(PyrRunOnAct.meanAvgFRProfile2to3s_Stim_Inact))],...
        [PyrRunOnAct.meanAvgFRProfile2to3s_NonStimCtrl_Inact,...
        PyrRunOnAct.meanAvgFRProfile2to3s_Stim_Inact],...
        ['FRMean 2to3s' fnstr ' Inact'],...
        '', PyrRunOnAct.pRSAvgFRProfile2to3s_NonStimStim_Inact,...
        ['FRMean2to3sGoodNoStimVsStim' fnstr '_Inact'],...
        pathAnal0,colorSel,xlabels,xLimTmp);
